@startuml 12_sprint2_use_case
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle Hollow
skinparam usecase {
  BackgroundColor #EBF5FB
  BorderColor #2E74B5
}
skinparam actor {
  BackgroundColor #FEF9E7
  BorderColor #B7950B
}

actor "Administrateur" as Admin
actor "Technicien"     as Tech
actor "Client"         as Cli

Admin --|> Tech

rectangle " " {
  usecase "S'authentifier"      as UC_AUTH
  usecase "Gérer interventions" as UC_INTERV
  usecase "Gérer pannes"        as UC_PANNE
  usecase "Consulter planning"  as UC_PLANNING
}

Tech  --> UC_INTERV
Tech  --> UC_PLANNING
Admin --> UC_INTERV
Admin --> UC_PLANNING
Cli   --> UC_PANNE

UC_INTERV   ..> UC_AUTH : <<include>>
UC_PANNE    ..> UC_AUTH : <<include>>
UC_PLANNING ..> UC_AUTH : <<include>>

@enduml
